 export const cardArrivalData = [
  {
    imageUrl: "/blackshirt.png",
    title: "T-SHIRT WITH TAPE DETAILS",
    rating: 4,
    price: "$120",
  },
  {
    imageUrl: "/jeens.png",
    title: "SKINNY FIT JEANS",
    rating:5,
    price: "$240",
  },
  {
    imageUrl: "/tshirt.png",
    title: "CHECKERED SHIRT",
    rating: 3,
    price: "$180",
  },
  {
    imageUrl: "orangshirt.png",
    title: "SLEEVE STRIPED T-SHIRT",
    rating: 4,
    price: "$130",
  },
];

export const TopsellingData = [
  {
    imageUrl: "/blackshirt.png",
    title: "T-SHIRT WITH TAPE DETAILS",
    rating: 4,
    price: "$120",
  },
  {
    imageUrl: "/jeens.png",
    title: "SKINNY FIT JEANS",
    rating: 5,
    price: "$240",
  },
  {
    imageUrl: "/tshirt.png",
    title: "CHECKERED SHIRT",
    rating: 3,
    price: "$180",
  },
  {
    imageUrl: "orangshirt.png",
    title: "SLEEVE STRIPED T-SHIRT",
    rating: 4,
    price: "$130",
  },
]


export const  FilteredProducts  = [
  { id:" 1",
    imageUrl: "/blackshirt.png",
    title: "T-SHIRT WITH TAPE DETAILS",
    rating: 4,
    price: "$120",
  },
  {
    id:"2",
    imageUrl: "/jeens.png",
    title: "SKINNY FIT JEANS",
    rating: 5,
    price: "$240",
  },
  {id:"3",
    imageUrl: "/tshirt.png",
    title: "CHECKERED SHIRT",
    rating: 3,
    price: "$180",
  },
  {id :"4",
    imageUrl: "orangshirt.png",
    title: "SLEEVE STRIPED T-SHIRT",
    rating: 4,
    price: "$130",
  },
  {id:"5",
    imageUrl: "/blackshirt.png",
    title: "T-SHIRT WITH TAPE DETAILS",
    rating: 4,
    price: "$120",
  },
  {id:"6",
    imageUrl: "/jeens.png",
    title: "SKINNY FIT JEANS",
    rating: 5,
    price: "$240",
  },
  {id:"7",
    imageUrl: "/tshirt.png",
    title: "CHECKERED SHIRT",
    rating: 3,
    price: "$180",
  },
  {id:"8",
    imageUrl: "orangshirt.png",
    title: "SLEEVE STRIPED T-SHIRT",
    rating: 4,
    price: "$130",
  },
  {id :"9",
    imageUrl: "/blackshirt.png",
    title: "T-SHIRT WITH TAPE DETAILS",
    rating: 4,
    price: "$120",
  },
  // {id:"10",
  //   imageUrl: "/jeens.png",
  //   title: "SKINNY FIT JEANS",
  //   rating: 5,
  //   price: "$240",
  // },
  // {id:"11",
  //   imageUrl: "/tshirt.png",
  //   title: "CHECKERED SHIRT",
  //   rating: 3,
  //   price: "$180",
  // },
  // {id:"12",
  //   imageUrl: "orangshirt.png",
  //   title: "SLEEVE STRIPED T-SHIRT",
  //   rating: 4,
  //   price: "$130",
  // },

]

